### ISSUE TITLE
Lab Report 3 Feedback

### ISSUE THREAD

**Issue by farnaf** [PeterEckmann1/cse15l-lab-reports#3]
Here is your feedback for Lab Report 3 - Copy whole directories with `scp -r`:

- [x] Show copying your whole markdown-parse directory to your `ieng6` account
- [x] Show logging into your `ieng6` account after doing this and compiling and running the tests for your repository
- [x] Show (like in the last step of the first lab) combining `scp`, `;`, and `ssh` to copy the whole directory and run the tests in one line.
  - is there another command to make sure you can run the tests remotely? 

Additional comments from your grader:
nice job 😃
feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by PeterEckmann1** [comment]
I'm not sure what you mean by another command to run the tests remotely... the lab writeup just mentions using scp to copy the files and ssh to run them. Could I get some clarification on what commands to add to make this work? I'm mainly confused as to why sshing into the server and then running the commands works, but not running the ssh as a one-liner. Thanks!

**Comment by farnaf** [comment]
Thanks for commenting!

Seems like you were unable to do the running of tests in a single command because of the issues with `ssh cs15lwi22alx@ieng6.ucsd.edu "cd markdown-parse/; make test"`. Could you try a different command using other solutions suggested in [this Piazza post](https://piazza.com/class/kxs0toocqhv4og?cid=354)

**Comment by PeterEckmann1** [comment]
Thanks, I wasn't aware of that Piazza post. Should be fixed now, and I updated the lab report: https://petereckmann1.github.io/cse15l-lab-reports/lab-report-3-week-6.html
