### ISSUE TITLE
Lab Report 4 Feedback

### ISSUE THREAD

**Issue by enzohnnn** [PeterEckmann1/cse15l-lab-reports#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [x] Provides link to the markdown-parse repository they reviewed

Snippet 1

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 2

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 3

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [ ] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Additional comments from your grader:

Feel free to comment below any questions about the rubric/feedback
You don't show the output of running yours on your third snippet even though you said it works. How would I know?
--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by PeterEckmann1** [comment]
What should I show to prove that the test passes? JUnit doesn't have any output to indicate a specific test passed, only when a specific test fails.

**Comment by PeterEckmann1** [comment]
@enzohnnn I noticed I got a 0/1 on gradescope. Could I get some idea as to what I need to put to prove that the test passes? The writeup just says "if it passed, say so"... what else do I do besides "say so?" Thanks!

**Comment by enzohnnn** [comment]
If you show your terminal output saying all your JUnit tests passed I have been accepting that as good enough proof from others. :)

**Comment by PeterEckmann1** [comment]
Ok, added, thank you!
